default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: 1234

development:
  <<: *default
  database: alice_Web_development

test:
  <<: *default
  database: alice_Web_test
 
production:
  <<: *default
  database: alice_Web_production